### ISSUE TITLE
Could not parse BB-Tag

### ISSUE THREAD

**Issue by ghost** [owt5008137/WP-Code-Highlight.js#10]
There has a bug in current version(0.5.0), could not parse [code][/code] even enabled bb-tag support.
The line 411 in file wp_code_highlight.js.php

``` php
if (hljs_get_lib_option('shortcode')) {
```

The **hljs_get_lib_option** should be **hljs_get_option**

**Comment by ghost** [comment]
Sorry, not line 411 it's line 410

**Comment by owent** [comment]
Thanks and I'll fix it in 0.5.1
