### ISSUE TITLE
Should delete  all the br tags which belong to BBCode

### ISSUE THREAD

**Issue by ghost** [owt5008137/WP-Code-Highlight.js#11]
When putting out the contents of article, WP will add br for every line without deleting \n. Pre will be used  when parsing BBCode  and every paragraph will wrap  line which causes addition of line spacing.

BBCode
![bbcode](https://cloud.githubusercontent.com/assets/9904376/10429797/bd66439a-712d-11e5-8bed-4d6ff671f150.png)

pre-code
![pre-code](https://cloud.githubusercontent.com/assets/9904376/10429798/bda946c2-712d-11e5-9f22-9a879ff0f2c6.png)

The hljs_code_handler function

``` php
function hljs_code_handler($atts, $content) {
    $language = '';
    if (!empty($atts['lang']))
        $language = "class=\"${atts['lang']}\"";
    return "<pre class=\"hljs\"><code $language>" . ltrim(str_replace('<br />', '', $content), '\n') . '</code></pre>';
}
```

**Comment by owent** [comment]
@arthas2014 thanks for your suggest.But you can check the option **"Highlight.js Option - Use BR:"** to use `<br />` instead of "\n" as EOL.
