### ISSUE TITLE
Can't add code indentation in tinyMCE

### ISSUE THREAD

**Issue by pieroit** [owt5008137/WP-Code-Highlight.js#14]
When writing code inside [code]...[/code] I can't find a way to insert code indentation. If I hit the TAB button the focus changes; if I insert special chars like `&nbsp;` they are deleted. Behaviour is not consistent if I start to switch from Visual to Text editor and back.

How can code bi indented properly?
If you have a solution I can code it myself and then PR

Thanks!!!

**Comment by owent** [comment]
I don't use bbcode and so test less using bbcode.But I checked the code and find no problem.

```
/**
 * Add BB-Tag for highlighting.
 *
 *   Usage: [CODE lang=cpp]...[/CODE]
 */
function hljs_code_handler($atts, $content) {
    $language = '';
    if (!empty($atts['lang']))
        $language = "class=\"${atts['lang']}\"";
    return "<pre class=\"hljs\"><code $language>" . ltrim($content, '\n') . '</code></pre>';
}
if (hljs_get_option('shortcode')) {
    add_shortcode('code', 'hljs_code_handler');
}

```

It's better if you can RP, and I will check it later.

**Comment by pieroit** [comment]
Right, using `<pre><code>...</code></pre>` the spaces inserted in the snippet remain saved.
Insert this text into the `Text` tab of TinyMCE to repeat the errror:

```
The following code uses pre + code tags:
<pre><code>
var ok = function( e ) {
    return e*e;
};
</code></pre>
This next part uses the shortcode

[code]
var ok = function( e ) {
    return e*e;
};
[/code]
```

If you save the post from the `Text` tab everything goes fine, but if you switch to `Visual` the spaces in the bbcode disappear.
I guess it's tinyMCE intruding into the bbcode content, before it gets saved. So no problem on the PHP side...
