### ISSUE TITLE
行号|复制

### ISSUE THREAD

**Issue by lzuliuyun** [owt5008137/WP-Code-Highlight.js#17]
可以支持行号显示，并双击复制粘贴吗？

**Comment by owent** [comment]
@lzuliuyun 我这里只是对highlight.js做了一层包装，适配Wordpress，行号支持得要highlight.js支持才行呦。详见 http://highlightjs.readthedocs.io/en/latest/line-numbers.html

关于双击复制粘贴的话，我也并没有给highlight.js动手脚的计划，建议你可以去[highlight.js](https://github.com/isagalaev/highlight.js/)提issue，如果它有新增这个选项，我会加进插件里的

**Comment by lzuliuyun** [comment]
@owt5008137  好的，qqq~
