### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by hysg** [owt5008137/WP-Code-Highlight.js#19]
使用markdown，代码内不支持换行，所有代码都挤到一行了。怎么解决？

**Comment by owent** [comment]
@hysg 你得markdown是把代码生成在&lt;pre&gt;里的吗？或者，如果不是的话，可以勾选上**Highlight.js Option - Use BR:**这个选项。这样highlight.js就会使用&lt;br /&gt;标签作为换行符。

默认&lt;pre&gt;里换行符就是\n。如果是css把换行符换了也最好换回来。
