### ISSUE TITLE
Baidu CDN option does not work

### ISSUE THREAD

**Issue by NoAnyLove** [owt5008137/WP-Code-Highlight.js#2]
Baidu CDN does not host highlight.js ver 8.4 anymore, the latest version hosted is 8.2.

**Comment by owent** [comment]
@NoAnyLove  I have send request to baidu static cdn repository(https://github.com/Clouda-team/baiducdnstatic) and it will be merged some times later. I suggest you to use other cdns before that.

**Comment by owent** [comment]
@NoAnyLove Baidu CDN using ver 8.2 now.(temporary)
