### ISSUE TITLE
Worpress 4.7.3 无法选择其他语言

### ISSUE THREAD

**Issue by akring** [owt5008137/WP-Code-Highlight.js#21]
设置页面选中了一些其他的语言，例如Swift和Lua，但是点击保存按钮，页面刷新后勾选项又没了，而且实际对Swift代码的高亮也没有生效

**Comment by owent** [comment]
@akring 你好，我刚刚自测了一下并没有出现你说的这个问题。
请问你用的是本地模式而不是CDN吗？如果用得是CDN，是用哪个CDN呢？

另外你点击保存之后有提示
```
配置保存成功
```
```
生成highlight.js自定义高亮语言包完成
```
这两行吗？

这个插件如果内容分发来源是本地/local，并且包是Custom的时候，会在插件目录生成语言包文件，所以请确保wordpress对插件目录有写权限。另外设置完之后并不会影响wordpress的缓存系统，比如：如果你有使用WP Super Cache，那么已有页面缓存过期和浏览器的js缓存过期前可能仍然会使用老的

**Comment by akring** [comment]
我也自查了一下，应该就是使用了Custom，而我对插件目录没有写权限造成的，更换为百度CDN之后重新测试成功，感谢您的回复

**Comment by owent** [comment]
@akring 我会增加对写失败时的提示，也谢谢报这个issue
