### ISSUE TITLE
WP 4.7.4 class not added

### ISSUE THREAD

**Issue by Daredzik** [owt5008137/WP-Code-Highlight.js#22]
Hi, clean version of WP 4.7.4
Theme: hueman.

Class: hljs not added to pre element, but only to code.

**Comment by owent** [comment]
So, what's the problem?
According to https://highlightjs.org/static/demo/
***hljs*** should only be added to code element.

**Comment by Daredzik** [comment]
Ohh i see, but custom css in plugin options, have `pre.hljs {padding: 5px;}`.
Then i thought, it should have this class ;)

here: https://github.com/owt5008137/WP-Code-Highlight.js/blob/master/wp_code_highlight.js.php#L94

**Comment by owent** [comment]
@Daredzik Yes, it's just a old sample, I will remove it later.

**Comment by Daredzik** [comment]
@owt5008137 then my bad, sorry ;)

**Comment by Daredzik** [comment]
@owt5008137 if u use [code] [/code] class `.hljs` is added to pre element

**Comment by owent** [comment]
@Daredzik thanks and I will fix it later

**Comment by owent** [comment]
Fixed and published.
