### ISSUE TITLE
Hooking into `wp_head` and not `wp_enqueue_scripts`

### ISSUE THREAD

**Issue by ghost** [owt5008137/WP-Code-Highlight.js#23]
Hello. Neat plugin. HLJS is super cool. I noticed this plugin hooks into `wp_head` instead of `wp_enqueue_scripts` with the following line of code:

```php
add_action('wp_head', 'hljs_include');
```

As I understand it `wp_enqueue_scripts` is where most themes hook in and I believe where plugins typically hook in as well to load. Is there a reason not to hook into `wp_enqueue_scripts`?

**Comment by owent** [comment]
It's a historical issue. We didn't use `wp_enqueue_script` before. 

We use `wp_enqueue_script` just after wordpress support multisite, and just replaced the ways to import script and style with `wp_enqueue_script` and `wp_enqueue_style`.

**Comment by ghost** [comment]
Thanks for the info. I was curious because I'm building a plugin and used `wp_head` at first as it seemed the logical choice for my circumstances and was curious to know why others might do it as I've had difficulty finding information as I'm self-teaching. Appreciate the info and background. Please keep up the great work. HLJS is one hell of a cool library!
