### ISSUE TITLE
插件还更新不？

### ISSUE THREAD

**Issue by jgh004** [owt5008137/WP-Code-Highlight.js#26]
有没有打算更新一下，支持 wp 5.0?

**Comment by owent** [comment]
@jgh004 我已经不用 wordpress了。手边没有环境的说，如果你可以提供一个临时环境的话，我可以更新适配下看看。顺便还能更新一波 hightlight.js 版本

**Comment by owent** [comment]
近期已更新 0.6.3 ,因为一个安全问题，插件被暂时关闭了。我已经更新并向wordpress申请重开了，可能要等一段时间
